export const WORKOUT_LOGS_STORAGE_KEY = 'loic-marathon-workout-logs-v1'
export const SCHEDULE_OVERRIDES_STORAGE_KEY = 'loic-marathon-schedule-overrides-v1'
export const PLAN_OVERRIDES_STORAGE_KEY = 'loic-marathon-plan-overrides-v1'
export const FUELING_PREFERENCES_STORAGE_KEY = 'loic-marathon-fueling-preferences-v1'
export const GROCERY_CHECKS_STORAGE_KEY = 'loic-marathon-grocery-checks-v1'
export const NOTIFICATION_PREFERENCES_STORAGE_KEY = 'loic-marathon-notification-preferences-v1'
export const LOCAL_PUSH_SUBSCRIPTION_STORAGE_KEY = 'loic-marathon-local-push-subscription-v1'
export const NOTIFICATION_SYNC_METADATA_STORAGE_KEY =
  'loic-marathon-notification-sync-metadata-v1'
export const THEME_STORAGE_KEY = 'loic-marathon-theme'
